import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import { log } from "next-axiom";

const logThings = () => {
  console.log("hello world");
  console.warn("Here a warning");
  console.error("Here an error");

  log.debug("new sign-in challenge", { customerId: 32423, auth: "session" });
};

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <div className={styles.grid}>
          <button onClick={logThings}>
            <h2>Log Something &rarr;</h2>
          </button>
        </div>
        <div className={styles.grid}>
          <button
            onClick={() =>
              log.error("An Error", {
                userId: "fff",
                accountId: "0.0.4444",
                network: "testnet",
              })
            }
          >
            <h2>Log an error &rarr;</h2>
          </button>
        </div>
        <div className={styles.grid}>
          <button
            onClick={() =>
              log.info("Some info", {
                userId: "qqq",
                accountId: "0.0.4446",
                network: "testnet",
              })
            }
          >
            <h2>Log info &rarr;</h2>
          </button>
        </div>
        <div className={styles.grid}>
          <button
            onClick={() =>
              log.warn("An warning", {
                userId: "zzzz",
                accountId: "0.0.4447",
                network: "testnet",
              })
            }
          >
            <h2>Log Something &rarr;</h2>
          </button>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
